### ISSUE TITLE
How to resolve version conflicts between the current plugin and @ capacitor mlkit/barcode scanning? Here is the prompt log

### ISSUE THREAD

**Issue by UTSOURCE** [dragermrb/capacitor-plugin-media-capture#12]
How to resolve version conflicts between the current plugin and @ capacitor mlkit/barcode scanning?
Here is the prompt log

2024-06-06 17:25:20.068   411-411   AndroidRuntime          io.ionic.starter                     E  FATAL EXCEPTION: main
                                                                                                    Process: io.ionic.starter, PID: 411
                                                                                                    java.lang.NoSuchMethodError: No interface method getConfig(Landroidx/camera/core/impl/UseCaseConfigFactory$CaptureType;)Landroidx/camera/core/impl/Config; in class Landroidx/camera/core/impl/UseCaseConfigFactory; or its super classes (declaration of 'androidx.camera.core.impl.UseCaseConfigFactory' appears in /data/app/~~yuo0dpPWAZRAUVInswmAIw==/io.ionic.starter-aDHXU7qDYUM-0DK6PjE_kA==/base.apk)
                                                                                                    	at androidx.camera.video.VideoCapture.getDefaultConfig(VideoCapture.java:343)
                                                                                                    	at androidx.camera.core.internal.CameraUseCaseAdapter.getConfigs(CameraUseCaseAdapter.java:482)
                                                                                                    	at androidx.camera.core.internal.CameraUseCaseAdapter.addUseCases(CameraUseCaseAdapter.java:208)
                                                                                                    	at androidx.camera.lifecycle.LifecycleCamera.bind(LifecycleCamera.java:206)
                                                                                                    	at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:278)
                                                                                                    	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:532)
                                                                                                    	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
                                                                                                    	at com.whiteguru.capacitor.plugin.mediacapture.fragments.CaptureFragment.bindCaptureUsecase(CaptureFragment.kt:168)
                                                                                                    	at com.whiteguru.capacitor.plugin.mediacapture.fragments.CaptureFragment.access$bindCaptureUsecase(CaptureFragment.kt:53)
                                                                                                    	at com.whiteguru.capacitor.plugin.mediacapture.fragments.CaptureFragment$initCameraFragment$1.invokeSuspend(CaptureFragment.kt:307)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
                                                                                                    	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:74)
                                                                                                    	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:111)
                                                                                                    	at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda$2$lambda$1(DispatchQueue.kt:99)
                                                                                                    	at androidx.lifecycle.DispatchQueue.$r8$lambda$1ME-FmJywCV2uxhp8ajM5a9C_oI(Unknown Source:0)
                                                                                                    	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:223)
                                                                                                    	at android.os.Looper.loop(Looper.java:324)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8599)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6ca7ff4, Dispatchers.Main.immediate]
2024-06-06 17:25:20.091   411-411   Process                 io.ionic.starter                     I  Sending signal. PID: 411 SIG: 9

**Comment by dragermrb** [comment]
Do you have a sample repo to review?

**Comment by UTSOURCE** [comment]
@dragermrb https://github.com/UTSOURCE/capture

**Comment by UTSOURCE** [comment]
@dragermrb May I ask if there is a problem?

**Comment by dragermrb** [comment]
Sorry, I haven't had time to see it yet.

**Comment by UTSOURCE** [comment]
https://medium.com/mindorks/android-launch-mode-787d28952959
Is it related to this

**Comment by UTSOURCE** [comment]
Thank you for the reminder
