### ISSUE TITLE
App Crash when click record button 

### ISSUE THREAD

**Issue by ChanDru-Balu** [dragermrb/capacitor-plugin-media-capture#7]
Iam using following code :

`  async recordVideo(){
    this.platform.ready().then(async ()=>{
      try {
        // Create an options object
        const options: CaptureVideoOptions = {
          duration: 10, // Specify the duration of the video capture
          quality: 'uhd'  // Specify the video quality
        };
        const result = await MediaCapture.captureVideo(options);
        console.log('Captured video:', result);
        // Handle the captured video as needed
      } catch (error) {
        console.error('Error capturing video:', error);
      }
    })
  }`

But when I click the record button the app crashed without any error log.

I am using Ionic 7 , Capacitor v5.
and "@whiteguru/capacitor-plugin-media-capture": "^5.0.2"

**Comment by dragermrb** [comment]
Can you attach logcat errors?

**Comment by robin-alundi** [comment]
I get the following error, while trying to start the recorder.

java.lang.NoSuchMethodError: No interface method getConfig(Landroidx/camera/core/impl/UseCaseConfigFactory$CaptureType;)Landroidx/camera/core/impl/Config; in class Landroidx/camera/core/impl/UseCaseConfigFactory; or its super classes (declaration of 'androidx.camera.core.impl.UseCaseConfigFactory' appears in /data/app/~~EhJzVKSQQtgc3ExVQyQ53w==/io.ionic.starter-U7VVioCgFOPBlA6Va2jTbw==/base.apk)
	at androidx.camera.video.VideoCapture.getDefaultConfig(VideoCapture.java:343)
	at androidx.camera.core.internal.CameraUseCaseAdapter.getConfigs(CameraUseCaseAdapter.java:482)
	at androidx.camera.core.internal.CameraUseCaseAdapter.addUseCases(CameraUseCaseAdapter.java:208)
	at androidx.camera.lifecycle.LifecycleCamera.bind(LifecycleCamera.java:206)
	at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:278)
	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:532)
	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
	at com.whiteguru.capacitor.plugin.mediacapture.fragments.CaptureFragment.bindCaptureUsecase(CaptureFragment.kt:168)
	at com.whiteguru.capacitor.plugin.mediacapture.fragments.CaptureFragment.access$bindCaptureUsecase(CaptureFragment.kt:53)
	at com.whiteguru.capacitor.plugin.mediacapture.fragments.CaptureFragment$initCameraFragment$1.invokeSuspend(CaptureFragment.kt:307)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:74)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:111)
	at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda$2$lambda$1(DispatchQueue.kt:99)
	at androidx.lifecycle.DispatchQueue.$r8$lambda$1ME-FmJywCV2uxhp8ajM5a9C_oI(Unknown Source:0)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8324)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by dragermrb** [comment]
Hi @robin-alundi 

Do you have any repo with a sample project to look arround?

**Comment by robin-alundi** [comment]
I don't unfortunately, the error occurred when I triggered the captureVideo function.

**Comment by dragermrb** [comment]
Let me know if you create a sample repository I can review

**Comment by robin-alundi** [comment]
I just made a sample project and it works perfectly fine there, but I tried again in my original project and there the error occured again, while using the same line of code.
